"""
Monte Carlo wrapper for the Jeddah Islamic Port traffic model.

IMPORTANT
---------
This module uses the SAME SimPy simulation engine as main.py.

The Monte Carlo does NOT recreate the traffic model analytically.

Each replication:
    1. Generates its own random seed.
    2. Calls main.run_simulation(...)
    3. Extracts ONLY the maximum physical queue at each gate.
    4. Returns the gate congestion results.

The main.py file is NOT modified.

The Monte Carlo is parallelised using multiprocessing because each
replication is completely independent.
"""

from __future__ import annotations

import contextlib
import io
import multiprocessing as mp
from concurrent.futures import ProcessPoolExecutor

from copy import deepcopy

import numpy as np
import pandas as pd


# ============================================================
# PERCENTILES
# ============================================================

PERCENTILES = {
    "P10": 0.10,
    "P50": 0.50,
    "P90": 0.90,
    "P95": 0.95,
    "P99": 0.99,
}


# ============================================================
# SHARE UTILITIES
# ============================================================

def _normalise_shares(values):
    """
    Normalise a dictionary of shares so that they sum to 1.
    """

    values = {
        str(k): max(float(v), 0.0)
        for k, v in values.items()
    }

    total = sum(values.values())

    if total <= 0:
        raise ValueError("Shares must sum to a positive value.")

    return {
        k: v / total
        for k, v in values.items()
    }


def _perturb_shares(base, rng, variability):
    """
    Apply controlled multiplicative variation to shares.

    If variability = 0, the original scenario shares are preserved
    exactly.
    """

    base = _normalise_shares(base)

    if variability <= 0:
        return base

    keys = list(base.keys())

    raw = np.array(
        [
            base[k]
            * np.exp(
                rng.normal(
                    0.0,
                    float(variability),
                )
            )
            for k in keys
        ],
        dtype=float,
    )

    raw /= raw.sum()

    return {
        k: float(v)
        for k, v in zip(keys, raw)
    }


def _build_realisation_shares(
    base_terminal_shares,
    base_cargo_shares,
    rng,
    variability,
):
    """
    Create one stochastic terminal/cargo realisation.

    With variability = 0, the scenario is preserved exactly.
    """

    realised_terminal = _perturb_shares(
        base_terminal_shares,
        rng,
        variability,
    )

    realised_cargo = {}

    for terminal, shares in base_cargo_shares.items():

        realised_cargo[terminal] = _perturb_shares(
            shares,
            rng,
            variability,
        )

    return (
        realised_terminal,
        realised_cargo,
    )


# ============================================================
# GATE QUEUE EXTRACTION
# ============================================================

def _extract_peak_gate_queues(
    result,
    gates,
):
    """
    Extract the maximum physical queue at each gate.

    This uses the SAME queue_stock dataframe generated by main.py.

    No other KPI is calculated.
    """

    queue_stock = result.get(
        "queue_stock",
        None,
    )

    peaks = {
        gate: 0.0
        for gate in gates
    }

    if queue_stock is None:
        return peaks

    if queue_stock.empty:
        return peaks

    required_columns = {
        "gate",
        "queue_stock",
    }

    if not required_columns.issubset(
        queue_stock.columns
    ):
        return peaks

    # One groupby instead of filtering the dataframe separately
    # for every gate.
    grouped = (
        queue_stock
        .groupby("gate")["queue_stock"]
        .max()
    )

    for gate in gates:

        if gate in grouped.index:

            value = grouped.loc[gate]

            if pd.notna(value):
                peaks[gate] = float(value)

    return peaks


# ============================================================
# SINGLE SIMULATION WORKER
# ============================================================

def _run_single_simulation(task):
    """
    Execute ONE real SimPy replication.

    IMPORTANT:
    The worker imports main itself rather than passing the module
    through multiprocessing, because Python modules are not safely
    pickled between processes.
    """

    import main as model

    (
        simulation_number,
        simulation_seed,
        scenario,
    ) = task

    # --------------------------------------------------------
    # Read scenario
    # --------------------------------------------------------

    trucks_per_day = scenario["trucks_per_day"]

    arrival_variability = scenario["arrival_variability"]

    management_enabled = scenario["management_enabled"]

    max_entries_per_hour = scenario["max_entries_per_hour"]

    average_speed_kmh = scenario["average_speed_kmh"]

    lanes_per_direction = scenario["lanes_per_direction"]

    capacity_per_lane_vph = scenario["capacity_per_lane_vph"]

    n2_n1_corridor_lanes = scenario["n2_n1_corridor_lanes"]

    route_randomization = scenario["route_randomization"]

    demand_variability = scenario["demand_variability"]

    # --------------------------------------------------------
    # Generate scenario-specific shares
    # --------------------------------------------------------

    rng = np.random.default_rng(
        int(simulation_seed)
    )

    (
        realised_terminal_shares,
        realised_cargo_shares,
    ) = _build_realisation_shares(
        base_terminal_shares=scenario["terminal_shares"],
        base_cargo_shares=scenario["cargo_shares"],
        rng=rng,
        variability=demand_variability,
    )

    # --------------------------------------------------------
    # Run REAL SimPy model
    # --------------------------------------------------------

    # main.py prints a lot of information after every run.
    # Suppress it during Monte Carlo.
    with contextlib.redirect_stdout(
        io.StringIO()
    ):

        result = model.run_simulation(

            # ------------------------------------------------
            # Demand
            # ------------------------------------------------

            trucks_per_day=int(
                trucks_per_day
            ),

            # ------------------------------------------------
            # Randomisation
            # ------------------------------------------------

            route_randomization=float(
                route_randomization
            ),

            seed=int(
                simulation_seed
            ),

            arrival_time_variability=float(
                arrival_variability
            ),

            # ------------------------------------------------
            # Gate configuration
            # ------------------------------------------------

            entry_gate_rules=deepcopy(
                scenario["entry_gate_rules"]
            ),

            exit_gate_rules=deepcopy(
                scenario["exit_gate_rules"]
            ),

            entry_access_rules=deepcopy(
                scenario["entry_access_rules"]
            ),

            gate_lanes=deepcopy(
                scenario["gate_lanes"]
            ),

            gate_times_sec=deepcopy(
                scenario["gate_times_sec"]
            ),

            # ------------------------------------------------
            # Road configuration
            # ------------------------------------------------

            average_speed_kmh=float(
                average_speed_kmh
            ),

            lanes_per_direction=int(
                lanes_per_direction
            ),

            capacity_per_lane_vph=int(
                capacity_per_lane_vph
            ),

            n2_n1_corridor_lanes=int(
                n2_n1_corridor_lanes
            ),

            # ------------------------------------------------
            # Junctions
            # ------------------------------------------------

            junctions=deepcopy(
                scenario["junctions"]
            ),

            # ------------------------------------------------
            # Appointment management
            # ------------------------------------------------

            appointment_management_enabled=bool(
                management_enabled
            ),

            max_entries_per_hour=int(
                max_entries_per_hour
            ),

            # ------------------------------------------------
            # Routing
            # ------------------------------------------------

            route_overrides=deepcopy(
                scenario["route_overrides"]
            ),

            # ------------------------------------------------
            # Logistics
            # ------------------------------------------------

            logistics_destination_daily=deepcopy(
                scenario["logistics_destination_daily"]
            ),

            # ------------------------------------------------
            # Terminal / cargo
            # ------------------------------------------------

            terminal_shares=deepcopy(
                realised_terminal_shares
            ),

            cargo_shares=deepcopy(
                realised_cargo_shares
            ),

            # ------------------------------------------------
            # IMPORTANT
            # ------------------------------------------------

            save_outputs=False,
        )

    # --------------------------------------------------------
    # Extract ONLY gate congestion
    # --------------------------------------------------------

    gates = list(
        scenario["gate_lanes"].keys()
    )

    peak_queue = _extract_peak_gate_queues(
        result=result,
        gates=gates,
    )

    # --------------------------------------------------------
    # Return one compact result
    # --------------------------------------------------------

    row = {
        "simulation": simulation_number,
        "seed": int(simulation_seed),
        "daily_demand": int(trucks_per_day),
    }

    for gate in gates:

        row[
            f"peak_queue_{gate}"
        ] = peak_queue.get(
            gate,
            0.0,
        )

    # Overall maximum across gates
    row[
        "peak_queue_all"
    ] = max(
        peak_queue.values()
    ) if peak_queue else 0.0

    return row


# ============================================================
# PERCENTILE SUMMARY
# ============================================================

def _percentile_summary(
    df,
    columns,
):
    """
    Calculate P10 / P50 / P90 / P95 / P99
    for gate congestion.
    """

    metrics = {}

    for column in columns:

        if column not in df.columns:
            continue

        values = pd.to_numeric(
            df[column],
            errors="coerce",
        ).dropna()

        if values.empty:

            metrics[column] = {
                percentile: 0.0
                for percentile in PERCENTILES
            }

        else:

            metrics[column] = {
                percentile: float(
                    values.quantile(q)
                )
                for percentile, q
                in PERCENTILES.items()
            }

    return metrics


# ============================================================
# MONTE CARLO
# ============================================================

def run_monte_carlo(
    model,

    simulations=1000,

    # --------------------------------------------------------
    # Scenario inputs
    # --------------------------------------------------------

    trucks_per_day=None,

    arrival_variability=None,

    demand_variability=0.0,

    management_enabled=None,

    max_entries_per_hour=None,

    seed=42,

    # --------------------------------------------------------
    # Gate configuration
    # --------------------------------------------------------

    entry_gate_rules=None,

    exit_gate_rules=None,

    entry_access_rules=None,

    gate_lanes=None,

    gate_times_sec=None,

    # --------------------------------------------------------
    # Road configuration
    # --------------------------------------------------------

    average_speed_kmh=None,

    lanes_per_direction=None,

    capacity_per_lane_vph=None,

    n2_n1_corridor_lanes=None,

    # --------------------------------------------------------
    # Routing
    # --------------------------------------------------------

    route_overrides=None,

    route_randomization=None,

    # --------------------------------------------------------
    # Logistics
    # --------------------------------------------------------

    logistics_destination_daily=None,

    # --------------------------------------------------------
    # Junctions
    # --------------------------------------------------------

    junctions=None,

    # --------------------------------------------------------
    # Terminal / cargo
    # --------------------------------------------------------

    terminal_shares=None,

    cargo_shares=None,

    # --------------------------------------------------------
    # Parallelisation
    # --------------------------------------------------------

    workers=None,
):
    """
    Run Monte Carlo simulations using the REAL JIP SimPy model.

    The ONLY KPI calculated is gate congestion:

        peak_queue_G1
        peak_queue_G4
        peak_queue_G6
        peak_queue_G8
        peak_queue_G9
        ...

    The actual traffic simulation remains entirely inside main.py.
    """

    # ========================================================
    # VALIDATION
    # ========================================================

    simulations = int(
        simulations
    )

    if simulations < 1:
        raise ValueError(
            "simulations must be at least 1"
        )

    # ========================================================
    # READ DEFAULTS FROM main.py
    # ========================================================

    if trucks_per_day is None:

        trucks_per_day = int(
            model.TRUCK_MOVEMENTS_PER_DAY
        )

    if arrival_variability is None:

        arrival_variability = float(
            model.ARRIVAL_TIME_RANDOMIZATION
        )

    if management_enabled is None:

        management_enabled = bool(
            model.APPOINTMENT_MANAGEMENT_ENABLED
        )

    if max_entries_per_hour is None:

        max_entries_per_hour = int(
            model.MAX_PORT_ENTRIES_PER_HOUR
        )

    if average_speed_kmh is None:

        average_speed_kmh = float(
            model.AVERAGE_SPEED_KMH
        )

    if lanes_per_direction is None:

        lanes_per_direction = int(
            model.LANES_PER_DIRECTION
        )

    if capacity_per_lane_vph is None:

        capacity_per_lane_vph = int(
            model.CAPACITY_PER_LANE_VPH
        )

    if n2_n1_corridor_lanes is None:

        n2_n1_corridor_lanes = int(
            model.N2_N1_CORRIDOR_LANES
        )

    if route_randomization is None:

        route_randomization = float(
            model.ROUTE_RANDOMIZATION
        )

    # ========================================================
    # FREEZE SCENARIO
    # ========================================================

    base_entry_rules = deepcopy(
        entry_gate_rules
        if entry_gate_rules is not None
        else model.ENTRY_GATE_RULES
    )

    base_exit_rules = deepcopy(
        exit_gate_rules
        if exit_gate_rules is not None
        else model.EXIT_GATE_RULES
    )

    base_access_rules = deepcopy(
        entry_access_rules
        if entry_access_rules is not None
        else model.ENTRY_ACCESS_RULES
    )

    base_gate_lanes = deepcopy(
        gate_lanes
        if gate_lanes is not None
        else model.GATE_LANES
    )

    base_gate_times = deepcopy(
        gate_times_sec
        if gate_times_sec is not None
        else model.GATE_TIMES_SEC
    )

    base_route_overrides = deepcopy(
        route_overrides
        if route_overrides is not None
        else model.ROUTE_OVERRIDES
    )

    base_logistics_destination = deepcopy(
        logistics_destination_daily
        if logistics_destination_daily is not None
        else model.LOGISTICS_DESTINATION_DAILY
    )

    base_junctions = deepcopy(
        junctions
        if junctions is not None
        else model.JUNCTIONS
    )

    base_terminal_shares = deepcopy(
        terminal_shares
        if terminal_shares is not None
        else model.TERMINAL_SHARES
    )

    base_cargo_shares = deepcopy(
        cargo_shares
        if cargo_shares is not None
        else model.CARGO_SHARES
    )

    # ========================================================
    # BUILD IMMUTABLE SCENARIO FOR WORKERS
    # ========================================================

    scenario = {
        "trucks_per_day":
            int(trucks_per_day),

        "arrival_variability":
            float(arrival_variability),

        "demand_variability":
            float(demand_variability),

        "management_enabled":
            bool(management_enabled),

        "max_entries_per_hour":
            int(max_entries_per_hour),

        "average_speed_kmh":
            float(average_speed_kmh),

        "lanes_per_direction":
            int(lanes_per_direction),

        "capacity_per_lane_vph":
            int(capacity_per_lane_vph),

        "n2_n1_corridor_lanes":
            int(n2_n1_corridor_lanes),

        "route_randomization":
            float(route_randomization),

        "entry_gate_rules":
            base_entry_rules,

        "exit_gate_rules":
            base_exit_rules,

        "entry_access_rules":
            base_access_rules,

        "gate_lanes":
            base_gate_lanes,

        "gate_times_sec":
            base_gate_times,

        "route_overrides":
            base_route_overrides,

        "logistics_destination_daily":
            base_logistics_destination,

        "junctions":
            base_junctions,

        "terminal_shares":
            base_terminal_shares,

        "cargo_shares":
            base_cargo_shares,
    }

    # ========================================================
    # GENERATE INDEPENDENT SEEDS
    # ========================================================

    master_rng = np.random.default_rng(
        int(seed)
    )

    seeds = master_rng.integers(
        0,
        2_147_483_647,
        size=simulations,
        dtype=np.int64,
    )

    tasks = [
        (
            simulation_number,
            int(simulation_seed),
            scenario,
        )
        for simulation_number, simulation_seed
        in enumerate(seeds, start=1)
    ]

    # ========================================================
    # NUMBER OF WORKERS
    # ========================================================

    if workers is None:

        cpu_count = mp.cpu_count()

        # Leave one CPU free for the dashboard / operating system.
        workers = max(
            1,
            cpu_count - 1,
        )

    workers = int(workers)

    workers = max(
        1,
        min(
            workers,
            simulations,
        ),
    )

    # ========================================================
    # RUN PARALLEL MONTE CARLO
    # ========================================================

    # Spawn is safer for Streamlit / Windows environments.
    context = mp.get_context(
        "spawn"
    )

    records = []

    with ProcessPoolExecutor(
        max_workers=workers,
        mp_context=context,
    ) as executor:

        for result in executor.map(
            _run_single_simulation,
            tasks,
        ):

            records.append(
                result
            )

    # ========================================================
    # RESULTS DATAFRAME
    # ========================================================

    df = pd.DataFrame(
        records
    )

    # Keep simulations in their original order.
    if "simulation" in df.columns:

        df = df.sort_values(
            "simulation"
        ).reset_index(
            drop=True
        )

    # ========================================================
    # GATE KPI COLUMNS ONLY
    # ========================================================

    gates = list(
        base_gate_lanes.keys()
    )

    metric_columns = [
        f"peak_queue_{gate}"
        for gate in gates
    ]

    # Overall peak can also be useful.
    metric_columns.append(
        "peak_queue_all"
    )

    metric_columns = [
        column
        for column in metric_columns
        if column in df.columns
    ]

    # ========================================================
    # PERCENTILES
    # ========================================================

    metrics = _percentile_summary(
        df,
        metric_columns,
    )

    # ========================================================
    # REPRESENTATIVE SCENARIO
    # ========================================================

    # For gate-only analysis, the representative scenario is
    # simply the simulation closest to the median overall
    # maximum gate queue.

    representative = {}

    if not df.empty:

        target = float(
            df[
                "peak_queue_all"
            ].median()
        )

        distance = (
            df[
                "peak_queue_all"
            ] - target
        ).abs()

        idx = int(
            distance.idxmin()
        )

        representative = (
            df.loc[idx]
            .to_dict()
        )

    # ========================================================
    # GATE CAPACITY METADATA
    # ========================================================

    gate_capacities = {}

    for gate, lanes_cfg in base_gate_lanes.items():

        for operation in (
            "entry",
            "exit",
        ):

            key = (
                f"{gate} "
                f"{operation.upper()}"
            )

            lanes = int(
                lanes_cfg.get(
                    operation,
                    0,
                )
            )

            gate_capacities[key] = {
                "lanes": lanes,
                "configured": True,
            }

    # ========================================================
    # RETURN
    # ========================================================

    return {

        # One row per real SimPy replication
        "results":
            df,

        # P10 / P50 / P90 / P95 / P99
        # for gate congestion only
        "metrics":
            metrics,

        # Actual simulation closest to median
        "representative":
            representative,

        # Static gate information
        "gate_capacities_vph":
            gate_capacities,

        # Kept for compatibility with the existing dashboard
        "gate_probabilities":
            {},

        # No network calculations
        "network_capacity_vph":
            {},

        "network_links":
            [],
    }
